import {
    Video,
    Mic,
    Monitor,
    Settings,
    MoreVertical,
    X,
    Play,
    Pause,
    Square,
    Image as ImageIcon,
    FolderOpen,
    Trash2,
    Edit2,
    Download,
    Upload,
    RefreshCw,
    Camera,
    Maximize2,
    Minimize2,
    Home,
    Check,
    ChevronRight,
    ChevronDown,
    Volume2,
    VolumeX,
    FastForward,
    Rewind,
    Scissors,
    Save
} from 'lucide-react';

export const Icons = {
    Video,
    Mic,
    Audio: Mic,
    Screen: Monitor,
    Settings,
    More: MoreVertical,
    Close: X,
    Play,
    Pause,
    Stop: Square,
    Gallery: ImageIcon,
    Folder: FolderOpen,
    Delete: Trash2,
    Edit: Edit2,
    Download,
    Upload,
    Flip: RefreshCw,
    Camera,
    Maximize: Maximize2,
    Minimize: Minimize2,
    Home,
    Check,
    ChevronRight,
    ChevronDown,
    Volume: Volume2,
    Mute: VolumeX,
    Forward: FastForward,
    Rewind,
    Trim: Scissors,
    Save
};
